name: Deploy to Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # 创建部署目录（如果不存在）
          mkdir -p /var/www/vue3-app
          
          # 停止可能运行的nginx服务
          sudo systemctl stop nginx || true
          
          # 备份当前版本（如果存在）
          if [ -d "/var/www/vue3-app/current" ]; then
            sudo mv /var/www/vue3-app/current /var/www/vue3-app/backup-$(date +%Y%m%d-%H%M%S)
          fi
          
          # 创建新的部署目录
          sudo mkdir -p /var/www/vue3-app/current
          
    - name: Upload build files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "dist/*"
        target: "/var/www/vue3-app/current"
        strip_components: 1
        
    - name: Configure Nginx and restart services
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # 创建nginx配置文件
          sudo tee /etc/nginx/conf.d/vue3-app.conf > /dev/null <<EOF
          server {
              listen 8083;
              server_name _;
              root /var/www/vue3-app/current;
              index index.html;
              
              # 处理Vue Router的history模式
              location / {
                  try_files \$uri \$uri/ /index.html;
              }
              
              # 静态资源缓存
              location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                  expires 1y;
                  add_header Cache-Control "public, immutable";
              }
              
              # 安全头
              add_header X-Frame-Options "SAMEORIGIN" always;
              add_header X-Content-Type-Options "nosniff" always;
              add_header X-XSS-Protection "1; mode=block" always;
          }
          EOF
          
          # 测试nginx配置
          sudo nginx -t
          
          # 启动nginx服务
          sudo systemctl start nginx
          sudo systemctl enable nginx
          
          # 设置防火墙规则（如果防火墙开启）
          sudo firewall-cmd --permanent --add-service=http || true
          sudo firewall-cmd --permanent --add-service=https || true
          sudo firewall-cmd --reload || true
          
          # 设置目录权限
          sudo chown -R nginx:nginx /var/www/vue3-app
          sudo chmod -R 755 /var/www/vue3-app
          
          echo "部署完成！"
          echo "应用已部署到: http://${{ secrets.SERVER_HOST }}" 
